#  ╔════════════════════════════════════════════════════════════════════════════════════════════════╗
#  ║ ███████╗░█████╗░░█████╗░███╗░░██╗░█████╗░███╗░░░███╗██╗░░░██╗██████╗░██╗░░░░░██╗░░░██╗░██████╗ ║
#  ║ ██╔════╝██╔══██╗██╔══██╗████╗░██║██╔══██╗████╗░████║╚██╗░██╔╝██╔══██╗██║░░░░░██║░░░██║██╔════╝ ║
#  ║ █████╗░░██║░░╚═╝██║░░██║██╔██╗██║██║░░██║██╔████╔██║░╚████╔╝░██████╔╝██║░░░░░██║░░░██║╚█████╗░ ║
#  ║ ██╔══╝░░██║░░██╗██║░░██║██║╚████║██║░░██║██║╚██╔╝██║░░╚██╔╝░░██╔═══╝░██║░░░░░██║░░░██║░╚═══██╗ ║
#  ║ ███████╗╚█████╔╝╚█████╔╝██║░╚███║╚█████╔╝██║░╚═╝░██║░░░██║░░░██║░░░░░███████╗╚██████╔╝██████╔╝ ║
#  ║ ╚══════╝░╚════╝░░╚════╝░╚═╝░░╚══╝░╚════╝░╚═╝░░░░░╚═╝░░░╚═╝░░░╚═╝░░░░░╚══════╝░╚═════╝░╚═════╝░ ║
#  ╚════════════════════════════════════════════════════════════════════════════════════════════════╝

# EconomyPlus made by _ItsWagPvP
# Watch the full resource on https://github.com/ItsWagPvP/EconomyPlus

# Do not change this
Version: ${project.version}

# What language file do you want to use?
# You can select from the file in EconomyPlus/messages folder
# for now is available EN, IT, RO, AL, DE
Language: EN

# bStats system (https://bstats.org/plugin/bukkit/EconomyPlus/11565)
Metrics: true

# It will send to console plugin's internal logs
Debug-Mode: false

# Controls if EconomyPlus need to connect to another plugin for more features
Hooks:
  # Placeholders
  PlaceholderAPI: true
  HolographicDisplays: true

# You want to enable the updater?
# You will receive notifications in game and on the console if you have the permission (economyplus.update)
Updater: true

# Play to the player the sounds in front of success / error
Sounds:
  Use: true
  Success: ENTITY_PLAYER_LEVELUP
  Error: ENTITY_VILLAGER_NO

# Used to format the %economyplus_money_formatted% placeholder
# 1000 = 1k
# 1000000 = 1M
# 1000000000 = 1B
# 1000000000000 = 1T
# 1000000000000000 = 1Q
Format:
  k: "k"
  M: "M"
  B: "B"
  T: "T"
  Q: "Q"

# Set a user balance on join
Starting-Balance: 0.00

# Set a user bank on join
Starting-Bank-Balance: 0.00

# Use the decimal
# If true it's 0.00, if false is 0
Decimals: true

# Baltop configuration
Baltop:
  # This will work only with %money% and not with %money_formatted%
  Pattern:
    Enabled: false
    Value: "###.###,##"
  Chat:
    # Like 1) _ItsWagPvP: $100
    Player-Format: "&6%number%) &f%player%: &c$%money%"
    # The header of /baltop
    Header:
      - '&8&m-----------------'
      - '&d&lBalTop (Page %page%)'
      - '&8&m-----------------'
  # This is for the hologram! (/ep hologram)
  Hologram:
    # Refresh rate of holograms!
    Refresh-Rate: 60 # <- In seconds
    Player-Format: "&6%number%) &f%player%: &c$%money%"
    Header:
      - '&8&m-----------------'
      - '&d&lBalTop'
      - '&8&m-----------------'

# Select how to storage the data
Database:
  # Cache settings for better db performances
  Cache:
    # How much frequently the plugin should refresh the cache?
    # Does not affect player moneys or placeholders
    # It's only for security purposes
    # Default: 300 = 5 Minutes
    Auto-Save: 300 # <- In seconds
    # How many frequently the cache needs to be
    # refreshed with the MySQL db?
    MySQL: 10 # <- In seconds
  # You can choose one from UUID or NICKNAME
  Mode: "UUID"
  # H2 (database.db)
  # MySQL
  # YAML (data.yml)
  Type: H2
  # If you have set Type to H2 or YAML you have to ignore this options
  # Localhost connection
  Host: localhost
  # Default is 3306
  Port: 3306
  # The user for use MySQL connection
  User: root
  # Password of the user
  Password: qwerty
  # Database name
  Database: EconomyPlus
  # If you have not set up the table the plugin will create it for you!
  Table: economy
  # If the plugin loses connection it will auto-reconnect to the database
  AutoReconnect: true
  # Using an SSL certificate?
  useSSL: false


# This is the section where you can customize the /bank command
Bank:
  # You want to use the bank feature?
  Enabled: true
  # Interests feature
  Interests:
    Enabled: true
    # How frequently the bank will add the interests?
    Time: 300 # <- In seconds!
    # Interest rate (%)
    Percentage: 10
    # The player needs to be online to receive the interest?
    Online-Player: false
