#  ╔════════════════════════════════════════════════════════════════════════════════════════════════╗
#  ║ ███████╗░█████╗░░█████╗░███╗░░██╗░█████╗░███╗░░░███╗██╗░░░██╗██████╗░██╗░░░░░██╗░░░██╗░██████╗ ║
#  ║ ██╔════╝██╔══██╗██╔══██╗████╗░██║██╔══██╗████╗░████║╚██╗░██╔╝██╔══██╗██║░░░░░██║░░░██║██╔════╝ ║
#  ║ █████╗░░██║░░╚═╝██║░░██║██╔██╗██║██║░░██║██╔████╔██║░╚████╔╝░██████╔╝██║░░░░░██║░░░██║╚█████╗░ ║
#  ║ ██╔══╝░░██║░░██╗██║░░██║██║╚████║██║░░██║██║╚██╔╝██║░░╚██╔╝░░██╔═══╝░██║░░░░░██║░░░██║░╚═══██╗ ║
#  ║ ███████╗╚█████╔╝╚█████╔╝██║░╚███║╚█████╔╝██║░╚═╝░██║░░░██║░░░██║░░░░░███████╗╚██████╔╝██████╔╝ ║
#  ║ ╚══════╝░╚════╝░░╚════╝░╚═╝░░╚══╝░╚════╝░╚═╝░░░░░╚═╝░░░╚═╝░░░╚═╝░░░░░╚══════╝░╚═════╝░╚═════╝░ ║
#  ╚════════════════════════════════════════════════════════════════════════════════════════════════╝

# EconomyPlus made by _ItsWagPvP
# Watch the full resource on https://github.com/ItsWagPvP/EconomyPlus

# Do not change this!
# This is used to verify your config version
Version: ${project.version}

# Credit to all translators for contributing.
# EN, IT, RO, AL, DE, ZH, FR, RU, ES
Language: EN

# bStats system (https://bstats.org/plugin/bukkit/EconomyPlus/11565)
Metrics: true

# Will send plugin's internal logs to console
Debug-Mode: false

# Controls if EconomyPlus needs to connect to another plugin for more features
Hooks:
  # Placeholders
  PlaceholderAPI: true
  HolographicDisplays: true

# You want to enable the updater?
Updater:
  Plugin-Updater: true # Whether you want to enable the plugin updater feature.
  Notifications: true # You will receive notifications when you join if you have the permission (economyplus.update)
  Config-Updater: true # Enables the config to be updated automatically.
  Check-GitHub: 1 # Amount of days before the server will check for release on GitHub. #0 will check github every start up

# Plays a sound to the player to indicate success / error upon an action
Sounds:
  Use: true
  Success: ENTITY_PLAYER_LEVELUP
  Error: ENTITY_VILLAGER_NO

# Require permissions for commands that aren't administrative?
Require-Basic-Permissions: true

# Invalid Users
Invalid-Users:
  Save-Names: true # Attempts to prevent "Invalid User" by saving usernames.
  Modify-Balance: false # Modify balances of players who haven't joined.
  Username-Limit: true # Limits the username to 16 char length and non symbols. (Excludes . for geyser plugin) (UNSAFE IF FALSE)

Formatting:
  Use-Decimals: true
  Have-Excessive-Zeros: false # 12 = 12.00
  Round-Decimals: false # 10.005 = 10.01

Formatted-Placeholder: # Used to format the %economyplus_money_formatted% & %money_formatted% placeholder
  1000: k
  1000000: M
  1000000000: B
  1000000000000: T
  1000000000000000: Q

# This will only work with %money% and not with %money_formatted%
Pattern:
  Enabled: true
  Value: '###,###.##'

# Set a user balance on join
Starting-Balance: 0

# Set a user bank on join
Starting-Bank-Balance: 0

# Baltop configuration
Baltop:
  Chat:
    # Like 1) _ItsWagPvP: $100
    Player-Format: '&6%number%) &f%player%: &c$%money%'
    # The header of /baltop
    Header:
      - '&8&m-----------------'
      - '&d&lBalTop (Page %page%)'
      - '&8&m-----------------'
  # This is for the hologram! (/ep hologram)
  Hologram:
    # Refresh rate of holograms!
    Refresh-Rate: 60 # <- In seconds
    Player-Format: '&6%number%) &f%player%: &c$%money%'
    Header:
      - '&8&m-----------------'
      - '&d&lBalTop'
      - '&8&m-----------------'

# Select how to storage the data
Database:
  # Cache settings for better db performances
  Cache:
    # How much frequently the plugin should refresh the cache?
    # Does not affect player moneys or placeholders
    # It's only for security purposes
    # Default: 300 = 5 Minutes
    Auto-Save: 300 # <- In seconds
    # How many frequently the cache needs to be
    # refreshed with the MySQL db?
    MySQL: 10 # <- In seconds
  # You can choose one from UUID or NICKNAME
  Mode: UUID
  # H2 (database.db)
  # MySQL
  # YAML (data.yml)
  Type: H2
  # If you have set Type to H2 or YAML you have to ignore this options
  # Localhost connection
  Host: localhost
  # Default is 3306
  Port: 3306
  # The user for use MySQL connection
  User: root
  # Password of the user
  Password: qwerty
  # Database name
  Database: EconomyPlus
  # If you have not set up the table the plugin will create it for you!
  Table: economy
  # If the plugin loses connection it will auto-reconnect to the database
  AutoReconnect: true
  # Using an SSL certificate?
  useSSL: false


# This is the section where you can customize the /bank command
Bank:
  # You want to use the bank feature?
  Enabled: true
  # Interests feature
  Interests:
    Enabled: true
    # How frequently the bank will add the interests?
    Time: 300 # <- In seconds!
    # Interest rate (%)
    Percentage: 10
    # The player needs to be online to receive the interest?
    Online-Player: true